const MAXIMUM_OCCUPANCY = 3;
const INITIAL_BALANCE = 0;
const MINIMUM_MEMBERS_REQUIRED = 2;
const FILENAME_POSITION = 2;

module.exports = {
  MAXIMUM_OCCUPANCY,
  INITIAL_BALANCE,
  MINIMUM_MEMBERS_REQUIRED,
  FILENAME_POSITION,
};
